name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 13.2
      run: sudo xcode-select -s /Applications/Xcode_13.2.app
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
